server:
   port: 8888
   context-path: /v1
   error:
      whitelabel:
         enabled: false


spring:
   application:
      name: shoppingmall-backend

   profiles:
      active: developer
      
   devtools:
      livereload:
         enabled: true
         
   http:
      encoding:
         charset: UTF-8
         enabled: true
         forced: true
         forced-request: true
         forced-response: true
         
   aop:
      auto: true
   aop-proxy-target-class: true
   
   datasource:
      platform: postgres
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.219.101:5432/shoppingmall_2
      username: shoppingmall
      password: shoppingmall
   
   messages:
      always-use-message-format: true
      basename: messages/messages_ko
      encoding: UTF-8
      
   zipkin:
      baseUrl: http://192.168.219.101:9411/
      
   sleuth:
      enabled: true
      sampler:
         probability: 1


mybatis:
   config-location: classpath:mybatis/configuration.xml


logging:
   config: classpath:logback.xml


security:
   user:
      name: test
      password: 5678
      